### ISSUE TITLE
Sadly not compatible with the latest Laravel 5.6

### ISSUE THREAD

**Issue by nclifton** [tsugiproject/tsugi-laravel-sample#1]
Hi,
Sadly tsugi/lib uses an older version of symfony to laravel 5.6. So you need to ensure you only use laravel 5.5.

**Comment by nclifton** [comment]
stale

**Comment by csev** [comment]
I am happy to update this - but I don't use Laravel so it is a low priority for me.  Perhaps I should archive it - WDYT?
